### ISSUE TITLE
Missing Custom Chapter Builder functions

### ISSUE THREAD

**Issue by kutyel** [dtwrks/elm-book-interop-elm-ui#4]
Currently there is no `ChapterBuilder` exported and no `render` function:

```elm
render : String -> ChapterBuilder state html -> ChapterCustom state html
render body (ChapterBuilder builder) =
    Chapter
        { builder | body = builder.body ++ body }
```

So this makes impossible to render `elm-ui` components with markdown documentation:

```elm
firstChapter : Chapter x
firstChapter =
    chapter "Button with elm-ui"
        |> renderComponent
            (myButton "Button" <| Just <| logAction "Button clicked!")
        |> render """
This is the code needed to render a button with `elm-ui`:        
"""
```

This breaks with a huge error 🚨
```
This function cannot handle the argument sent through the (|>) pipe:

52|     chapter "Button with elm-ui"
53|         |> renderComponent
54|             (myButton "Button" <| Just <| logAction "Button clicked!")
55|>        |> render """
56|>This is the code needed to render a button with `elm-ui`:
57|>"""

The argument is:

ElmBook.Internal.Chapter.ChapterCustom
state1
(Element (ElmBook.Internal.Msg.Msg state))

But (|>) is piping it to a function that expects:

ElmBook.Internal.Chapter.ChapterBuilder state html

Detected problems in 1 module.
```

**Comment by georgesboris** [comment]
Sorry about the ridiculous response time - I hope you managed to find the solution by now... but the thing is that `render` (and its variants) should be used as the final step of your chapter builder pipeline - if you wanna use components inside your markdown you should add those components with `withComponent`, like so:

```elm
chapter ""
  |> withComponent(..)
  |> render "<component />"
```

The `renderComponent` is just a shortcut for the exact same code I wrote above - for when you have just one component to be rendered and no markdown. The same would be said for `renderComponentList`. Makes sense?
