### ISSUE TITLE
Wrong order of style applying

### ISSUE THREAD

**Issue by kamil7x** [dtwrks/elm-book-interop-elm-ui#5]
Slack thread: https://elmlang.slack.com/archives/C4F9NBLR1/p1652170841577009

It looks like sometimes styles are applied in wrong order. Two identical components (only font-color differs) produces different results:
1. classes: ```cptr p-16-4 he height-px-40px fc-24-144-255-255 s e wc ccx ccy sbt notxt focusable```
resulting styles: 
![image](https://user-images.githubusercontent.com/7629808/167597053-c6390b8f-3b28-486d-9ffb-ce7180dc7756.png)
2. classes ```cptr p-15-4 he height-px-40px fc-255-255-255-255 s e wc ccx ccy sbt notxt focusable```
result: 
![image](https://user-images.githubusercontent.com/7629808/167597249-0ebf6cef-fd18-462b-ad24-22483762dd80.png)

I checked some scenarios, ad it happens when there is another component below in the tree. So if you e.g. have:
1. button with some color
2. button with aonther color
3. button with fancy color

second button will have fancy color, even though it's applied to third one

@georgesboris please take a look

**Comment by georgesboris** [comment]
Hey! I've continued the discussion on Slack so more people can contribute.
If needed we can get back here for changes on this package :) 

Thread link https://elmlang.slack.com/archives/C4F9NBLR1/p1652214817139239?thread_ts=1652170841.577009&cid=C4F9NBLR1

**Comment by georgesboris** [comment]
This issue seems to be resolved by patch 1.0.1. If it continues please let me know! 🙇
